spring:
  application:
    name: decision
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/customer
    username: user1
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  cloud:
    function:
      definition: handleCustomerCreated
    stream:
      bindings:
        handleCustomerCreated-in-0:
          destination: customer-topic
#          handleCustomerCreated-in-0:
#            consumer:
#              configuration:
#                value:
#                  serializer: org.springframework.kafka.support.serializer.JsonSerializer
        binder:
          brokers:
            - localhost:9092
      schemaRegistryClient:
        endpoint: "http://127.0.0.1:8081"
server:
  port: 8282

