spring:
  application:
    name: decision-microservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/customer
    username: user1
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  cloud:
    function:
      definition: functionRouter
    stream:
      function:
        routing:
          enabled: true
      bindings:
        functionRouter-in-0:
          destination: customer-topic
          group: ${spring.application.name}

server:
  port: 8282

